name: Current with Charmcraft main

on:
  schedule:
    - cron: "50 22 * * 0"
  pull_request:
    paths:
      - kubernetes/**
      - machine/**
    types:
      - ready_for_review
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  current:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v5
        with:
          path: initial-charms
      - name: Checkout Charmcraft
        uses: actions/checkout@v5
        with:
          repository: canonical/charmcraft
          path: charmcraft
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Charmcraft
        run: |
          sudo apt-get update
          cd charmcraft
          make setup
      - name: Generate charms
        run: |
          cd initial-charms
          CHARMCRAFT_DIR=../charmcraft uvx --from rust-just just init
          git add --all
          git diff --exit-code HEAD
